spring:
  application.name: hhplus-tdd2
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
